name: Push-to-EC2 instance

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v1

      # Step 2: Deploy the code to EC2 instance
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 3: Execute remote SSH commands
      - name: Executing remote SSH commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update the system
            sudo yum -y update
            
            # Install Apache
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd

            # Navigate to the project directory
            cd /home/ec2-user

            # Install Node.js and dependencies
            sudo yum install -y nodejs npm
            npm install

            # Build the React app
            sudo npm run build

            # Clean up the target directory
            sudo rm -rf /var/www/html/*

            # Move the new build files to the web server directory
            sudo mv build/* /var/www/html/

            # Restart Apache to apply changes
            sudo systemctl restart httpd
